services:
  db:
    image: postgres:16
    container_name: usuarios_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: usuarios
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d usuarios"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: usuarios_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
