version: "3.9"

services:
  db:
    image: postgres:16
    container_name: usuarios_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: usuarios_y_pasajeros
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d usuarios_y_pasajeros"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usuarios_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "50051:50051"

volumes:
  db_data:
